# typed: strict
# frozen_string_literal: true

# This file was generated by Homebrew.
# It is formatted with `brew style`.

class Ifai < Formula
  desc "AI-powered CLI with streaming code block rendering"
  homepage "https://github.com/peterfei/ifai"
  version "0.4.6"
  license "MIT"

  url "https://github.com/peterfei/ifai/releases/download/v0.4.6/ifai-x86_64-apple-darwin.gz"
  sha256 "22c5ac9e47034dd2442593362c50e30287c138588f608f5f7ecff724b29e1feb"

  def install
    bin.install "ifai"

    # 生成 shell 补全（可选）
    # bash_completion.install "completions/#{CLI_NAME}.bash" => "#{CLI_NAME}"
    # zsh_completion.install "completions/#{CLI_NAME}.zsh" => "_#{CLI_NAME}"
    # fish_completion.install "completions/#{CLI_NAME}.fish"
  end

  test do
    system "#{bin}/#{CLI_NAME}", "--version"
    system "#{bin}/#{CLI_NAME}", "help"
  end
end
